<<<<<<< HEAD
#thgis is the tutorial
=======
version: '3.8'

>>>>>>> 7d7e146d9d256c9ab23ec8e2fa12abe96418be88
services:
  frontend:
    build: .
    container_name: security-guard-container
    ports:
      - "8080:8080"